@startuml
left to right direction

actor Client
actor Administrateur

' Account Management
Client --> (Se connecter / Déconnecter)
Client --> (Créer compte client)

' Product Management
Client --> (Rechercher produits)
Client --> (Visualiser liste produits) : <<include>>
Client --> (Trier liste produits)
Client --> (Visualiser détail produit) : <<include>>

' Wishlist and Loyalty
Client --> (Gérer liste de souhaits)
Client --> (Gérer points fidélité) : <<extend>>

' Order History and Reviews
Client --> (Visualiser commandes passées)
Client --> (Rédiger avis) : <<include>>

' Cart Management
Client --> (Ajouter au panier)
Client --> (Gérer panier)

' Administrator Console
Administrateur --> (Ajouter / Supprimer produit)
Administrateur --> (Gérer les produits)
Administrateur --> (Répondre aux avis) : <<include>>

' Relation between Reviews and Responses
(Rédiger avis) <-- (Répondre aux avis) : <<include>>
@enduml