@startuml
skinparam {
    actorBackgroundColor LightBlue
    packageBackgroundColor LightBlue 
    usecaseBorderColor Black
    arrowColor DarkBlue
    UsecaseRectangleRounded true
}

actor Client

left to right direction

package "Gestion du compte" {
    Client -u-> (Créer un compte)
    Client -u-> (Se connecter)
    Client -u-> (Se déconnecter)
    Client -u-> (Rester connecté)
}

package "Navigation et filtres" {
    Client --> (Naviguer via un menu global)
    Client --> (Naviguer par regroupements de produits)
    Client --> (Voir les produits par catégorie)
    Client --> (Filtrer les produits par prix)
}

package "Consultation des produits" {
    Client --> (Faire défiler les articles sur la page d'accueil)
    Client --> (Consulter la description des produits)
    Client --> (Voir la quantité de stock disponible)
    Client --> (Voir les produits en rupture de stock)
    Client --> (Choisir la couleur du produit)
}

package "Achat" {
    Client -u-> (Acheter un lot)
    Client -u-> (Payer une commande)
    Client -u-> (Choisir le moyen de paiement)
}

package "Avis" {
    Client -u-> (Déposer un avis)
    Client -u-> (Consulter les avis)
}
@enduml
